on:
  push:
    branches:
      - develop

jobs:
  build-container:
    name: Build and push container
    secrets: inherit
    uses: EpayVNTech/workflow/.github/workflows/container_build_latest.yaml@develop
